version: '3.9'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    command: postgres -p 5432
    volumes:
      - database:/var/lib/postgresql/data

  hse_app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      DATASOURCE_NAME: postgres
      DATASOURCE_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "8000:8000"
volumes:
  database:
    driver: local
